const SetActionTypes = {
	RECEIVED_GAME_STATE: 'RECEIVED_GAME_STATE',
	TOGGLE_CARD: 'TOGGLE_CARD',
	SET_ATTEMPTED: 'SET_ATTEMPTED',
	SET_MADE: 'SET_MADE',
	OTHER_SET_MADE: 'OTHER_SET_MADE',
	NO_SET: 'NO_SET',

	REQUEST_TO_CREATE_PLAYER: 'REQUEST_TO_CREATE_PLAYER',
	CREATED_PLAYER: 'CREATED_PLAYER',

	RECEIVED_LOBBY_STATE: 'RECEIVED_LOBBY_STATE',

	REQUEST_JOIN_GAME: 'REQUEST_JOIN_GAME',
	JOINED_GAME: 'JOINED_GAME',
	
	REQUEST_CREATE_GAME: 'REQUEST_CREATE_GAME',
	CREATED_GAME: 'CREATED_GAME',

	REQUEST_START_GAME: 'REQUEST_START_GAME',
	STARTED_GAME: 'STARTED_GAME',
};

export default SetActionTypes;